"""empty message

Revision ID: 7d3554e73fa5
Revises: 6980739536d1
Create Date: 2021-09-26 10:33:24.349407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d3554e73fa5'
down_revision = '6980739536d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'jobs', ['id'])
    op.create_unique_constraint(None, 'zones', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zones', type_='unique')
    op.drop_constraint(None, 'jobs', type_='unique')
    # ### end Alembic commands ###
